<template>
    <div>
        <page-main>
            <h2>警告！！此页面一般情况非管理员不可见</h2>
            <h2>警告！！此页面一般情况非管理员不可见</h2>
            <h3>非指定用户访问也会长生访问记录</h3>
        </page-main>
    </div>
</template>
